import { TRPCError } from '@trpc/server';
import { schema } from '@udyamflow/db';
import { and, eq } from 'drizzle-orm';
import { z } from 'zod';
import {
  CashfreeError,
  cashfreeCheckoutUrl,
  cashfreeConfigured,
  cashfreeCreateOrder,
  cashfreeCreateVendor,
  cashfreeFetchVendor,
  cashfreeRefund,
  vendorIdForOrg,
} from '../cashfree';
import { isValidGstin, isValidIfsc, isValidPan, normalizeIndianMobile } from '../gst/india';
import { requireOrgAdmin } from '../invoicing/issue';
import { getStripe } from '../stripe';
import { publicProcedure, router, tenantProcedure } from '../trpc';

// Stripe Connect onboarding details. Express accounts are the right default
// for SaaS — Stripe owns the dashboard, payouts, and KYC flow; we just
// handle bookings + checkout.

const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000';

// Per-region default routing: services priced in INR go through Cashfree
// (best UPI / Indian-banking coverage); everything else routes to Stripe.
// Both settle to the tenant: Stripe via their Connect account, Cashfree via
// their Easy Split vendor (see ../cashfree.ts). Until a tenant finishes
// either onboarding, payments fall back to the platform account — set
// CASHFREE_REQUIRE_VENDOR=true to refuse INR checkouts instead.

const INR_CURRENCIES = new Set(['INR']);

function pickProvider(currency: string): 'stripe' | 'cashfree' | 'none' {
  const upper = currency.toUpperCase();
  if (INR_CURRENCIES.has(upper)) {
    return process.env.CASHFREE_CLIENT_ID ? 'cashfree' : 'none';
  }
  return process.env.STRIPE_SECRET_KEY ? 'stripe' : 'none';
}

export const paymentRouter = router({
  // Quick check — does this booking need a checkout step?
  route: publicProcedure
    .input(z.object({ bookingId: z.string() }))
    .query(async ({ ctx, input }) => {
      const [booking] = await ctx.db
        .select({
          id: schema.booking.id,
          serviceId: schema.booking.serviceId,
          paymentStatus: schema.booking.paymentStatus,
        })
        .from(schema.booking)
        .where(eq(schema.booking.id, input.bookingId));
      if (!booking) throw new TRPCError({ code: 'NOT_FOUND' });
      if (!booking.serviceId) return { provider: 'none' as const, amount: 0, currency: 'USD' };

      const [svc] = await ctx.db
        .select({
          priceCents: schema.service.priceCents,
          currency: schema.service.currency,
        })
        .from(schema.service)
        .where(eq(schema.service.id, booking.serviceId));
      if (!svc || svc.priceCents === 0) {
        return { provider: 'none' as const, amount: 0, currency: 'USD' };
      }

      return {
        provider: pickProvider(svc.currency),
        amount: svc.priceCents,
        currency: svc.currency,
      };
    }),

  createCheckout: publicProcedure
    .input(z.object({ bookingId: z.string(), returnUrl: z.string().url() }))
    .mutation(async ({ ctx, input }) => {
      const [booking] = await ctx.db
        .select()
        .from(schema.booking)
        .where(eq(schema.booking.id, input.bookingId));
      if (!booking) throw new TRPCError({ code: 'NOT_FOUND' });
      if (!booking.serviceId) {
        throw new TRPCError({ code: 'BAD_REQUEST', message: 'No service on booking' });
      }

      const [svc] = await ctx.db
        .select()
        .from(schema.service)
        .where(eq(schema.service.id, booking.serviceId));
      if (!svc) throw new TRPCError({ code: 'NOT_FOUND', message: 'Service vanished' });

      const provider = pickProvider(svc.currency);
      if (provider === 'none') {
        throw new TRPCError({
          code: 'PRECONDITION_FAILED',
          message: 'No payment provider configured for this currency',
        });
      }

      if (provider === 'stripe') {
        const stripe = getStripe();
        if (!stripe) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR' });

        // Per-tenant Connect routing. If the tenant has finished Stripe
        // onboarding (charges_enabled), funds settle directly to their
        // account via the Stripe-Account header. Otherwise fall back to
        // the platform account so existing setups keep working.
        const [tenant] = await ctx.db
          .select({
            accountId: schema.tenantSettings.stripeAccountId,
            chargesEnabled: schema.tenantSettings.stripeChargesEnabled,
            invoiceProvider: schema.tenantSettings.invoiceProvider,
            autoInvoice: schema.tenantSettings.autoInvoice,
          })
          .from(schema.tenantSettings)
          .where(eq(schema.tenantSettings.organizationId, booking.organizationId));
        const connectAccount =
          tenant?.accountId && tenant.chargesEnabled ? tenant.accountId : undefined;
        // Tenants on built-in Stripe invoicing with auto-invoice on get a
        // paid invoice generated by Checkout itself; the webhook mirrors it
        // into our invoice table.
        const stripeInvoice =
          !!connectAccount && tenant?.invoiceProvider === 'stripe' && tenant.autoInvoice;

        const session = await stripe.checkout.sessions.create(
          {
            mode: 'payment',
            line_items: [
              {
                quantity: 1,
                price_data: {
                  currency: svc.currency.toLowerCase(),
                  unit_amount: svc.priceCents,
                  product_data: { name: svc.name },
                },
              },
            ],
            metadata: {
              bookingId: booking.id,
              organizationId: booking.organizationId,
            },
            ...(stripeInvoice
              ? {
                  customer_email: booking.customerEmail ?? undefined,
                  invoice_creation: {
                    enabled: true,
                    invoice_data: {
                      metadata: { bookingId: booking.id, organizationId: booking.organizationId },
                    },
                  },
                }
              : {}),
            success_url: `${input.returnUrl}?status=paid&booking=${booking.id}`,
            cancel_url: `${input.returnUrl}?status=cancelled&booking=${booking.id}`,
          },
          // `stripeAccount` makes Stripe route the API call against the
          // connected account — checkout session, payment intent, and
          // payout all live on the tenant's side of the ledger.
          connectAccount ? { stripeAccount: connectAccount } : undefined,
        );
        await ctx.db
          .update(schema.booking)
          .set({
            paymentStatus: 'pending',
            paymentProvider: 'stripe',
            paymentId: session.id,
          })
          .where(eq(schema.booking.id, booking.id));
        return { redirectUrl: session.url! };
      }

      // Cashfree. Split to the tenant's Easy Split vendor once it's ACTIVE
      // so the money settles to their bank, not the platform account.
      const [tenant] = await ctx.db
        .select({
          vendorId: schema.tenantSettings.cashfreeVendorId,
          vendorStatus: schema.tenantSettings.cashfreeVendorStatus,
        })
        .from(schema.tenantSettings)
        .where(eq(schema.tenantSettings.organizationId, booking.organizationId));
      const vendorId =
        tenant?.vendorId && tenant.vendorStatus === 'ACTIVE' ? tenant.vendorId : undefined;
      if (!vendorId && process.env.CASHFREE_REQUIRE_VENDOR === 'true') {
        throw new TRPCError({
          code: 'PRECONDITION_FAILED',
          message: 'This business has not finished setting up online payments yet',
        });
      }
      const { paymentSessionId } = await cashfreeCreateOrder({
        orderId: booking.id,
        amountPaise: svc.priceCents,
        currency: svc.currency,
        vendorId,
        customerName: booking.customerName,
        customerEmail: booking.customerEmail ?? undefined,
        customerPhone: booking.customerPhone ?? undefined,
        returnUrl: `${input.returnUrl}?status=paid&booking=${booking.id}`,
      });
      await ctx.db
        .update(schema.booking)
        .set({
          paymentStatus: 'pending',
          paymentProvider: 'cashfree',
          paymentId: paymentSessionId,
          paymentVendorId: vendorId ?? null,
        })
        .where(eq(schema.booking.id, booking.id));

      return { redirectUrl: cashfreeCheckoutUrl(paymentSessionId) };
    }),

  // Stripe Connect — Express onboarding. Reuses an existing account if one
  // was already created for this tenant; otherwise spins up a fresh one.
  // Returns a one-time onboarding URL the user should be redirected to.
  connectStripe: tenantProcedure.mutation(async ({ ctx }) => {
    const stripe = getStripe();
    if (!stripe) {
      throw new TRPCError({ code: 'PRECONDITION_FAILED', message: 'Stripe is not configured' });
    }

    const [tenant] = await ctx.db
      .select({ accountId: schema.tenantSettings.stripeAccountId })
      .from(schema.tenantSettings)
      .where(eq(schema.tenantSettings.organizationId, ctx.organizationId));

    let accountId = tenant?.accountId ?? null;
    if (!accountId) {
      const account = await stripe.accounts.create({
        type: 'express',
        metadata: { organizationId: ctx.organizationId },
        capabilities: {
          card_payments: { requested: true },
          transfers: { requested: true },
        },
      });
      accountId = account.id;
      await ctx.db
        .insert(schema.tenantSettings)
        .values({ organizationId: ctx.organizationId, stripeAccountId: accountId })
        .onConflictDoUpdate({
          target: schema.tenantSettings.organizationId,
          set: { stripeAccountId: accountId, updatedAt: new Date() },
        });
    }

    const link = await stripe.accountLinks.create({
      account: accountId,
      refresh_url: `${APP_URL}/settings/payments?stripe=refresh`,
      return_url: `${APP_URL}/settings/payments?stripe=done`,
      type: 'account_onboarding',
    });

    return { url: link.url };
  }),

  // Reads tenant-level Stripe status. Used by the settings page to show a
  // "Connected" / "Onboarding" / "Action required" badge without a Stripe
  // call from the browser.
  stripeStatus: tenantProcedure.query(async ({ ctx }) => {
    const [tenant] = await ctx.db
      .select({
        accountId: schema.tenantSettings.stripeAccountId,
        chargesEnabled: schema.tenantSettings.stripeChargesEnabled,
      })
      .from(schema.tenantSettings)
      .where(eq(schema.tenantSettings.organizationId, ctx.organizationId));
    return {
      accountId: tenant?.accountId ?? null,
      chargesEnabled: tenant?.chargesEnabled ?? false,
    };
  }),

  refund: tenantProcedure
    .input(z.object({ bookingId: z.string(), amount: z.number().int().min(1).optional() }))
    .mutation(async ({ ctx, input }) => {
      const [booking] = await ctx.db
        .select()
        .from(schema.booking)
        .where(
          and(
            eq(schema.booking.id, input.bookingId),
            eq(schema.booking.organizationId, ctx.organizationId),
          ),
        );
      if (!booking) throw new TRPCError({ code: 'NOT_FOUND' });
      if (booking.paymentStatus !== 'paid') {
        throw new TRPCError({ code: 'PRECONDITION_FAILED', message: 'Booking is not paid' });
      }
      if (!booking.paymentProvider || !booking.paymentId) {
        throw new TRPCError({ code: 'PRECONDITION_FAILED', message: 'No payment record' });
      }

      if (booking.paymentProvider === 'stripe') {
        const stripe = getStripe();
        if (!stripe) throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR' });

        // Connect-routed bookings live on the tenant's account. Look up
        // their Stripe account id so retrieve + refund hit the right side.
        const [tenant] = await ctx.db
          .select({ accountId: schema.tenantSettings.stripeAccountId })
          .from(schema.tenantSettings)
          .where(eq(schema.tenantSettings.organizationId, ctx.organizationId));
        const reqOpts = tenant?.accountId ? { stripeAccount: tenant.accountId } : undefined;

        // We stored the Checkout Session id; resolve to the underlying
        // payment_intent before refunding.
        // Stripe SDK: 3rd arg is RequestOptions (where stripeAccount goes);
        // 2nd is per-call query params. Pass an empty params object so the
        // RequestOptions arg lands in the right slot.
        const session = await stripe.checkout.sessions.retrieve(booking.paymentId, {}, reqOpts);
        const pi =
          typeof session.payment_intent === 'string'
            ? session.payment_intent
            : session.payment_intent?.id;
        if (!pi)
          throw new TRPCError({ code: 'NOT_FOUND', message: 'Stripe payment intent missing' });
        await stripe.refunds.create({ payment_intent: pi, amount: input.amount }, reqOpts);
      } else if (booking.paymentProvider === 'cashfree') {
        // Cashfree needs an explicit amount (rupees); default to the full
        // service price. Split orders recover the refund from the vendor.
        const [svc] = booking.serviceId
          ? await ctx.db
              .select({ priceCents: schema.service.priceCents })
              .from(schema.service)
              .where(eq(schema.service.id, booking.serviceId))
          : [];
        const amountPaise = input.amount ?? svc?.priceCents;
        if (!amountPaise) {
          throw new TRPCError({ code: 'BAD_REQUEST', message: 'Refund amount is required' });
        }
        try {
          await cashfreeRefund({
            orderId: booking.id,
            amountPaise,
            vendorId: booking.paymentVendorId,
          });
        } catch (err) {
          throw new TRPCError({
            code: 'BAD_GATEWAY',
            message: (err as Error).message.slice(0, 240),
            cause: err,
          });
        }
      }

      await ctx.db
        .update(schema.booking)
        .set({ paymentStatus: 'refunded' })
        .where(eq(schema.booking.id, booking.id));
      return { ok: true };
    }),

  // Cashfree Easy Split onboarding: registers the tenant as a vendor with
  // their payout account + KYC. Bank details go straight to Cashfree; we
  // only keep the vendor id, its status and a masked label.
  connectCashfree: tenantProcedure
    .input(
      z.object({
        name: z.string().min(2).max(100),
        email: z.email(),
        phone: z.string(),
        payout: z.discriminatedUnion('kind', [
          z.object({
            kind: z.literal('bank'),
            accountHolder: z.string().min(2).max(100),
            accountNumber: z.string().regex(/^\d{9,18}$/, 'Account number must be 9–18 digits'),
            ifsc: z.string().refine(isValidIfsc, 'Invalid IFSC code'),
          }),
          z.object({
            kind: z.literal('upi'),
            accountHolder: z.string().min(2).max(100),
            vpa: z.string().regex(/^[\w.-]{2,256}@[a-zA-Z]{2,64}$/, 'Invalid UPI ID'),
          }),
        ]),
        pan: z.string().refine(isValidPan, 'Invalid PAN'),
        gstin: z.string().refine(isValidGstin, 'Invalid GSTIN').optional(),
        accountType: z.string().min(2).max(40),
        businessType: z.string().min(2).max(60),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      await requireOrgAdmin(ctx.db, ctx.organizationId, ctx.user.id);
      if (!cashfreeConfigured()) {
        throw new TRPCError({ code: 'PRECONDITION_FAILED', message: 'Cashfree is not configured' });
      }
      const phone = normalizeIndianMobile(input.phone);
      if (!phone) {
        throw new TRPCError({ code: 'BAD_REQUEST', message: 'Enter a valid Indian mobile number' });
      }

      const [tenant] = await ctx.db
        .select({ vendorId: schema.tenantSettings.cashfreeVendorId })
        .from(schema.tenantSettings)
        .where(eq(schema.tenantSettings.organizationId, ctx.organizationId));
      if (tenant?.vendorId) {
        throw new TRPCError({
          code: 'CONFLICT',
          message: 'Payout account already registered. Contact support to change bank details.',
        });
      }

      const vendorId = vendorIdForOrg(ctx.organizationId);
      let state: Awaited<ReturnType<typeof cashfreeCreateVendor>>;
      try {
        state = await cashfreeCreateVendor({
          vendorId,
          name: input.name,
          email: input.email,
          phone,
          payout: input.payout,
          kyc: {
            accountType: input.accountType,
            businessType: input.businessType,
            pan: input.pan,
            gstin: input.gstin,
          },
        });
      } catch (err) {
        throw new TRPCError({
          code: err instanceof CashfreeError && err.status < 500 ? 'BAD_REQUEST' : 'BAD_GATEWAY',
          message: (err as Error).message.slice(0, 240),
          cause: err,
        });
      }

      const label =
        input.payout.kind === 'bank'
          ? `${input.payout.ifsc.slice(0, 4).toUpperCase()} ••${input.payout.accountNumber.slice(-4)}`
          : input.payout.vpa.replace(/^(.{2}).*(@.*)$/, '$1••$2');
      await ctx.db
        .insert(schema.tenantSettings)
        .values({
          organizationId: ctx.organizationId,
          cashfreeVendorId: state.vendorId,
          cashfreeVendorStatus: state.status,
          cashfreePayoutLabel: label,
        })
        .onConflictDoUpdate({
          target: schema.tenantSettings.organizationId,
          set: {
            cashfreeVendorId: state.vendorId,
            cashfreeVendorStatus: state.status,
            cashfreePayoutLabel: label,
            updatedAt: new Date(),
          },
        });
      return { status: state.status, remarks: state.remarks };
    }),

  // Current vendor status. `refresh` re-reads it from Cashfree (bank
  // verification is async), otherwise returns the cached value.
  cashfreeStatus: tenantProcedure
    .input(z.object({ refresh: z.boolean().default(false) }).default({ refresh: false }))
    .query(async ({ ctx, input }) => {
      const [tenant] = await ctx.db
        .select({
          vendorId: schema.tenantSettings.cashfreeVendorId,
          status: schema.tenantSettings.cashfreeVendorStatus,
          label: schema.tenantSettings.cashfreePayoutLabel,
        })
        .from(schema.tenantSettings)
        .where(eq(schema.tenantSettings.organizationId, ctx.organizationId));
      const base = {
        configured: cashfreeConfigured(),
        vendorId: tenant?.vendorId ?? null,
        status: tenant?.status ?? null,
        payoutLabel: tenant?.label ?? null,
        remarks: null as string | null,
      };
      if (!input.refresh || !tenant?.vendorId || !base.configured) return base;
      try {
        const latest = await cashfreeFetchVendor(tenant.vendorId);
        if (latest.status !== tenant.status) {
          await ctx.db
            .update(schema.tenantSettings)
            .set({ cashfreeVendorStatus: latest.status, updatedAt: new Date() })
            .where(eq(schema.tenantSettings.organizationId, ctx.organizationId));
        }
        return { ...base, status: latest.status, remarks: latest.remarks };
      } catch {
        return base;
      }
    }),
});
